#!/usr/bin/env node

/**
 * Script para hacer backup de la BD actual a SQL dump
 */

const mariadb = require('mariadb');
const fs = require('fs');

const pool = mariadb.createPool({
    host: 'localhost',
    user: 'root',
    password: 'sys81902root',
    database: 'tdc_db'
});

async function generateDump() {
    let conn;
    try {
        conn = await pool.getConnection();
        
        console.log('🔄 Generando backup de la base de datos...\n');
        
        let sqlContent = `/*M!999999\\- enable the sandbox mode */ 
-- MariaDB dump 10.19  Distrib 10.6.25-MariaDB, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: tdc_db
-- Generated by Node.js backup script on ${new Date().toISOString()}
-- Database synced with current state
--

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, @SQL_NOTES=0 */;

`;

        // Obtener todas las tablas que contienen datos importantes (no todas)
        const tablesToDump = [
            'bandas_artistas',
            'clientes',
            'solicitudes',
            'solicitudes_fechas_bandas',
            'solicitudes_talleres',
            'solicitudes_servicios',
            'eventos_confirmados',
            'eventos_lineup'
        ];

        for (const table of tablesToDump) {
            try {
                // Obtener datos
                const rows = await conn.query(`SELECT * FROM ${table}`);
                
                if (rows.length === 0) {
                    sqlContent += `\n--\n-- Dumping data for table \`${table}\`\n--\n\nLOCK TABLES \`${table}\` WRITE;\n`;
                    sqlContent += `/*!40000 ALTER TABLE \`${table}\` DISABLE KEYS */;\n`;
                    sqlContent += `/*!40000 ALTER TABLE \`${table}\` ENABLE KEYS */;\n`;
                    sqlContent += `UNLOCK TABLES;\n`;
                    continue;
                }

                sqlContent += `\n--\n-- Dumping data for table \`${table}\`\n--\n\nLOCK TABLES \`${table}\` WRITE;\n`;
                sqlContent += `/*!40000 ALTER TABLE \`${table}\` DISABLE KEYS */;\n`;

                // Obtener nombres de columnas
                const firstRow = rows[0];
                const columns = Object.keys(firstRow);
                
                sqlContent += `INSERT INTO \`${table}\` (\`${columns.join('`,`')}\`) VALUES\n`;

                // Procesar valores
                const valueRows = rows.map((row, idx) => {
                    const values = columns.map(col => {
                        const val = row[col];
                        if (val === null) return 'NULL';
                        if (typeof val === 'string') return "'" + val.replace(/'/g, "''") + "'";
                        if (val instanceof Date) return "'" + val.toISOString().split('T')[0] + "'";
                        return val;
                    });
                    return `(${values.join(',')})`;
                }).join(',\n  ');

                sqlContent += `  ${valueRows};\n`;
                
                sqlContent += `/*!40000 ALTER TABLE \`${table}\` ENABLE KEYS */;\n`;
                sqlContent += `UNLOCK TABLES;\n`;

                console.log(`✓ ${table}: ${rows.length} registros`);
            } catch (err) {
                console.log(`⚠ ${table}: ${err.message}`);
            }
        }

        sqlContent += `\n/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
`;

        // Guardar archivo
        const outputFile = '../database/mysqldump_latest.sql';
        fs.writeFileSync(outputFile, sqlContent, 'utf8');
        
        console.log(`\n✅ Backup completado: ${outputFile}`);
        console.log(`   Tamaño: ${(sqlContent.length / 1024).toFixed(2)} KB`);
        console.log(`   Líneas: ${sqlContent.split('\n').length}`);

    } catch (err) {
        console.error('❌ Error:', err.message);
    } finally {
        if (conn) conn.end();
        await pool.end();
    }
}

generateDump();
