# Versión final para desarrollo

FROM node:18-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia solo los archivos de dependencias para poder ejecutar npm install
# Estos archivos serán montados desde el host, pero los copiamos para construir la imagen.
COPY ../backend/package*.json ./

# Instala las dependencias. Esto creará /app/node_modules dentro de la imagen.
RUN npm install

# Expone el puerto
EXPOSE 3000

# El comando se ejecutará sobre los archivos montados desde el host.
CMD [ "node", "server.js" ]