# Usa la imagen oficial de Nginx
FROM nginx:alpine

# Copia los archivos estáticos de tu frontend al directorio de servicio de Nginx
COPY frontend/ /usr/share/nginx/html

# Copia la configuración personalizada de Nginx
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Expone los puertos 80 (HTTP) y 443 (HTTPS)
EXPOSE 80 443

# Nginx se iniciará por defecto, no necesitamos un CMD explícito aquí
