/*M!999999\- enable the sandbox mode */ 
-- MariaDB dump 10.19  Distrib 10.6.25-MariaDB, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: tdc_db
-- Generated by Node.js backup script on 2026-04-15T16:43:27.761Z
-- Database synced with current state
--

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, @SQL_NOTES=0 */;


--
-- Dumping data for table `bandas_artistas`
--

LOCK TABLES `bandas_artistas` WRITE;
/*!40000 ALTER TABLE `bandas_artistas` DISABLE KEYS */;
INSERT INTO `bandas_artistas` (`id_banda`,`nombre`,`genero_musical`,`bio`,`instagram`,`facebook`,`twitter`,`tiktok`,`web_oficial`,`youtube`,`spotify`,`descripcion`,`logo_url`,`foto_prensa_url`,`contacto_rol`,`id_cliente`,`verificada`,`activa`,`creado_en`,`actualizado_en`,`registrado_por_id_usuario`) VALUES
  (1,'Reite','Rock / Tributo','Tributo oficial a La Renga','@reitebanda','https://www.facebook.com/reitebanda','@reitebanda',NULL,'https://www.reitebanda.com','https://www.youtube.com/c/ReiteBanda','https://open.spotify.com/artist/reite',NULL,'/uploads/bandas/logo_reite.jpg',NULL,'Manager',8,1,1,'2026-03-13','2026-03-18',NULL),
  (2,'Pateando Bares','Rock Nacional','Rock nacional con trayectoria','@pateando.bares','https://www.facebook.com/pateandobaresoficial','@pateandooficial','@pateandooficial','https://www.pateandobares.com.ar','https://www.youtube.com/pateandobaresoficial','https://open.spotify.com/artist/pateandooficial',NULL,NULL,NULL,'Productor',9,1,1,'2026-03-13','2026-03-18',NULL),
  (3,'Las Mentas','Rock Alternativo','Banda femenina de rock alternativo','@lasmentasbanda','https://www.facebook.com/lasmentasbanda','@lasmentas_rock','@lasmentasbanda','https://www.lasmentas.com.ar','https://www.youtube.com/lasmentasbanda','https://open.spotify.com/artist/lasmentas',NULL,'/uploads/bandas/logo_las_mentas.jpeg',NULL,'Vocalista/Manager',10,1,1,'2026-03-13','2026-03-18',NULL),
  (4,'Cumbia Sudaka','Cumbia / Tropical','Banda telonera festiva','@cumbiasudaka','https://www.facebook.com/cumbiasudaka','@cumbiasudaka',NULL,NULL,'https://www.youtube.com/cumbiasudaka','https://open.spotify.com/artist/cumbiasudaka',NULL,NULL,NULL,'Líder',11,1,1,'2026-03-13','2026-03-18',NULL),
  (5,'Horcas','Heavy Metal / Thrash Metal','Banda histórica del heavy metal argentino fundada en 1988 por Osvaldo Civile, ex guitarrista de V8. Referente del metal nacional con extensa discografía y giras por todo el país.','@horcasoficial',NULL,NULL,NULL,NULL,'https://www.youtube.com/@horcasoficial','https://open.spotify.com/artist/horcas',NULL,'/uploads/bandas/logo_horcas.png',NULL,NULL,6,1,1,'2026-03-13','2026-03-18',NULL),
  (6,'Superlógico','Rock / Tributo a Patricio Rey','Banda tributo a Patricio Rey y sus Redonditos de Ricota con fuerte presencia en el circuito rockero del conurbano y CABA.','@superlogicotributo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_superlogico.jpeg',NULL,NULL,6,0,1,'2026-03-13','2026-03-28',NULL),
  (7,'Pier','Rock Nacional','Banda argentina de rock formada en los años 90, conocida por canciones populares dentro del rock barrial.','@pieroficial',NULL,NULL,NULL,NULL,'https://www.youtube.com/@pieroficial','https://open.spotify.com/artist/pier',NULL,NULL,NULL,NULL,6,1,1,'2026-03-13','2026-03-18',NULL),
  (8,'Rey Garufa','Rock / Tributo Redondos','Banda tributo a Patricio Rey y sus Redonditos de Ricota con fuerte presencia en el circuito de bares y festivales rockeros.','@reygarufatributo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (9,'Willy Quiroga','Rock / Hard Rock','Proyecto solista de Willy Quiroga, histórico bajista y cantante de Vox Dei, uno de los pioneros del rock argentino.','@willyquirogaoficial',NULL,NULL,NULL,NULL,'https://www.youtube.com/@willyquiroga','https://open.spotify.com/artist/willyquiroga',NULL,NULL,NULL,NULL,6,1,1,'2026-03-13','2026-03-18',NULL),
  (10,'Nomade 73','Rock Nacional','Banda de rock barrial del conurbano bonaerense con influencias del rock clásico argentino.','@nomade73',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_nomade_73.jpeg',NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (11,'Territorio Caníbal','Hardcore / Metal','Banda de hardcore metal del circuito under del Gran Buenos Aires con presentaciones frecuentes en festivales independientes.','@territoriocanibal',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_territorio_canibal.png',NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (12,'Ojo Animal','Stoner Rock / Hard Rock','Banda de stoner rock del circuito under argentino con influencias del hard rock clásico.','@ojoanimalband',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (13,'Falsa Euforia','Punk','Proyecto independiente del conurbano bonaerense dentro de la escena alternativa.','@falsaeuforia',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_falsa_euforia.jpg',NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (14,'Cronorock','Rock Nacional','Banda independiente de rock nacional con presentaciones en bares y festivales under.','@cronorock',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_cronorock.jpeg',NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (15,'Ratucha','Punk Rock','Banda punk del circuito under del conurbano bonaerense con fuerte presencia en festivales autogestionados.','@ratuchapunk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (16,'La Monky','Rock / Funk Rock','Banda independiente del circuito rockero del conurbano con influencias funk y rock alternativo.','@lamonkybanda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_la_monky.jpg',NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (17,'Raros Ratones','Rock Alternativo','Banda emergente de rock alternativo dentro de la escena under del Gran Buenos Aires.','@rarosratones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (18,'La Locomotora','Hard Rock',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_la_locomotora.png',NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (19,'Chat Tuchat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_chat_tuchat.png',NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (20,'Capitan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_capitan.png',NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (21,'El Centésimo Mono',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_el_centesimo_mono.jpeg',NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (22,'Industria','Punk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_industria.jpg',NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (23,'Guarilo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_guarilo.png',NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (24,'Le Debes Plata a la Banda','Rock',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_le_debes_plata_a_la_banda.jpeg',NULL,NULL,6,0,1,'2026-03-13','2026-03-18',NULL),
  (25,'Tricota','Rock',NULL,'@rocktricota',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_tricota.jpeg',NULL,NULL,6,0,1,'2026-03-18','2026-03-18',NULL),
  (26,'Nueva banda de prueba','Rap',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6,0,0,'2026-03-18','2026-04-09',NULL),
  (27,'Defensores de la fe','Metal',NULL,'@defensoresdelafe.ok',NULL,NULL,NULL,NULL,NULL,NULL,'Banda metal tributo a Judas Priest','/uploads/bandas/logo_defensores_de_la_fe.jpg',NULL,NULL,NULL,0,1,'2026-03-26','2026-03-28',NULL),
  (29,'India Madre','Metal',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,'2026-03-26','2026-03-26',NULL),
  (32,'Psycophobia','Thrash Metal',NULL,'@psycophobia_thrash',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_psycophobia.png',NULL,NULL,NULL,0,1,'2026-03-26','2026-03-28',NULL),
  (33,'KorGue','Metal Punk',NULL,'@korgue_metalpunk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'/uploads/bandas/logo_korgue.png',NULL,NULL,NULL,0,1,'2026-03-26','2026-03-28',NULL),
  (34,'Pánico','Rock tributo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'banda tributo a Jóvenes Pordioseros',NULL,NULL,NULL,6,0,1,'2026-04-09','2026-04-09',2),
  (35,'Cruz Diablo','Rock tributo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Banda tributo a Los redonditos de ricota',NULL,NULL,NULL,6,0,1,'2026-04-09','2026-04-09',2);
/*!40000 ALTER TABLE `bandas_artistas` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `clientes`
--

LOCK TABLES `clientes` WRITE;
/*!40000 ALTER TABLE `clientes` DISABLE KEYS */;
INSERT INTO `clientes` (`id_cliente`,`id_usuario`,`nombre`,`apellido`,`telefono`,`email`,`notas`,`creado_por_id_usuario`,`activo`,`creado_en`,`actualizado_en`) VALUES
  (1,NULL,'Juan','Pérez','+5491111111','juan@test.com',NULL,1,1,'2026-03-13','2026-03-13'),
  (2,NULL,'María','González','+5491111112','maria@test.com',NULL,1,1,'2026-03-13','2026-03-13'),
  (3,NULL,'Pedro','López','+5491111113','pedro@test.com',NULL,1,1,'2026-03-13','2026-03-13'),
  (4,NULL,'Ana','Rodríguez','+5491111114','ana@test.com',NULL,1,1,'2026-03-13','2026-03-13'),
  (5,NULL,'Carlos','Martínez','+5491111115','carlos@test.com',NULL,1,1,'2026-03-13','2026-03-13'),
  (6,2,'Rodrigo Villalba',NULL,NULL,'villalbarodrigo2009@gmail.com',NULL,2,1,'2026-03-18','2026-03-18'),
  (7,1,'Templo User',NULL,NULL,'temploclaypole@gmail.com',NULL,1,1,'2026-03-18','2026-03-18'),
  (8,NULL,'Juan','Reite','1155001122','reite.tributo@gmail.com','Rol en banda: Manager (migrado desde bandas_artistas.contacto_*)',NULL,1,'2026-03-18','2026-03-18'),
  (9,NULL,'Marco','Sández','1155003344','pateando.bares@gmail.com','Rol en banda: Productor (migrado desde bandas_artistas.contacto_*)',NULL,1,'2026-03-18','2026-03-18'),
  (10,NULL,'Sol','Rodríguez','1155005566','lasmentas@gmail.com','Rol en banda: Vocalista/Manager (migrado desde bandas_artistas.contacto_*)',NULL,1,'2026-03-18','2026-03-18'),
  (11,NULL,'Carlos','Mendoza','1144445566','cumbia.sudaka@gmail.com','Rol en banda: Líder (migrado desde bandas_artistas.contacto_*)',NULL,1,'2026-03-18','2026-03-18');
/*!40000 ALTER TABLE `clientes` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `solicitudes`
--

LOCK TABLES `solicitudes` WRITE;
/*!40000 ALTER TABLE `solicitudes` DISABLE KEYS */;
INSERT INTO `solicitudes` (`id_solicitud`,`categoria`,`id_cliente`,`id_usuario_creador`,`fecha_creacion`,`estado`,`es_publico`,`descripcion_corta`,`descripcion_larga`,`url_flyer`,`fecha_evento`,`hora_inicio`,`duracion_minutos`,`hora_fin`,`fecha_alternativa`,`actualizado_en`) VALUES
  (1,'ALQUILER',1,NULL,'2026-03-13','Solicitado',0,'Cumpleaños infantil 50 personas','Cumpleaños infantil para una niña de 8 años. Necesitamos inflable, servicio de cocinero y setup básico.',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-13'),
  (2,'ALQUILER',2,NULL,'2026-03-13','Confirmado',0,'Fiesta de 15 años - Servicio completo','Fiesta de 15 años. Contratamos servicio completo con meseras, bartender y sonido profesional.',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-13'),
  (3,'ALQUILER',3,NULL,'2026-03-13','Solicitado',0,'Baby shower 40 personas','Baby shower temático con 40 invitados. Necesitamos inflable de princesa y decoraciones.',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-13'),
  (4,'BANDAS',4,NULL,'2026-03-13','Confirmado',1,'Reite - Fecha Propia','Tributo a La Renga solicita fecha propia. Esperan público de 250 personas.',NULL,'2026-05-09','22:00:00',390,NULL,NULL,'2026-04-15'),
  (5,'BANDAS',5,NULL,'2026-03-13','Confirmado',1,'Las Mentas Show','Banda de rock femenino solicita fecha con formato de show abierto al público general.','/uploads/flyers/solicitud_5.jpg','2026-04-25',NULL,360,NULL,NULL,'2026-04-15'),
  (6,'BANDAS',4,NULL,'2026-03-13','Confirmado',1,'Termidor Fest','Rock nacional solicita fecha compartida con banda telonera. Esperan 200 personas.','/uploads/flyers/solicitud_6.jpeg','2026-04-18','21:00:00',450,NULL,NULL,'2026-04-15'),
  (7,'SERVICIOS',1,NULL,'2026-03-13','Solicitado',0,'Taller de Fotografía de Eventos','Taller teórico-práctico de fotografía profesional para eventos. 4 horas de instrucción.',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-13'),
  (8,'TALLERES',2,NULL,'2026-03-13','Confirmado',1,'Taller de Masaje Descontracturante','Sesión grupal de masaje descontracturante para empleados.',NULL,'2026-04-22','10:00:00',NULL,NULL,NULL,'2026-04-15');
/*!40000 ALTER TABLE `solicitudes` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `solicitudes_fechas_bandas`
--

LOCK TABLES `solicitudes_fechas_bandas` WRITE;
/*!40000 ALTER TABLE `solicitudes_fechas_bandas` DISABLE KEYS */;
INSERT INTO `solicitudes_fechas_bandas` (`id_solicitud`,`id_banda`,`fecha_evento`,`hora_evento`,`precio_basico`,`precio_final`,`precio_anticipada`,`precio_puerta`,`cantidad_bandas`,`expectativa_publico`,`bandas_json`,`fecha_alternativa`,`notas_admin`,`id_evento_generado`) VALUES
  (4,1,'2026-05-09','22:00:00','100000.00','120000.00','100000.00','120000.00',1,'250 personas','[{"id_banda":1,"nombre":"Reite","orden_show":1,"es_principal":true}]',NULL,NULL,NULL),
  (5,3,'2026-04-25','20:00:00','100000.00','120000.00','100000.00','120000.00',1,'180 personas','[{"id_banda":3,"nombre":"Las Mentas","orden_show":1,"es_principal":true}]',NULL,NULL,NULL),
  (6,2,'2026-04-18','21:30:00','120000.00','120000.00','100000.00','120000.00',3,'120','[{"id_banda":29,"nombre":"India Madre","orden_show":0,"es_principal":true},{"id_banda":33,"nombre":"KorGue","orden_show":1,"es_principal":false},{"id_banda":27,"nombre":"Defensores de la fe","orden_show":2,"es_principal":false}]',NULL,NULL,NULL);
/*!40000 ALTER TABLE `solicitudes_fechas_bandas` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `solicitudes_talleres`
--

LOCK TABLES `solicitudes_talleres` WRITE;
/*!40000 ALTER TABLE `solicitudes_talleres` DISABLE KEYS */;
INSERT INTO `solicitudes_talleres` (`id_solicitud_taller`,`id_solicitud`,`nombre_taller`,`fecha_evento`,`hora_evento`,`precio`) VALUES
  (1,8,'Masaje Descontracturante Grupal','2026-04-22','10:00:00','2500.00');
/*!40000 ALTER TABLE `solicitudes_talleres` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `solicitudes_servicios`
--

LOCK TABLES `solicitudes_servicios` WRITE;
/*!40000 ALTER TABLE `solicitudes_servicios` DISABLE KEYS */;
INSERT INTO `solicitudes_servicios` (`id_solicitud_servicio`,`id_solicitud`,`tipo_servicio`,`fecha_evento`,`hora_evento`,`precio`) VALUES
  (1,7,'Taller Educativo','2026-03-15','15:00:00','3000.00');
/*!40000 ALTER TABLE `solicitudes_servicios` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `eventos_confirmados`
--

LOCK TABLES `eventos_confirmados` WRITE;
/*!40000 ALTER TABLE `eventos_confirmados` DISABLE KEYS */;
INSERT INTO `eventos_confirmados` (`id`,`id_solicitud`,`tipo_evento`,`tabla_origen`,`nombre_evento`,`descripcion_corta`,`descripcion`,`fecha_evento`,`hora_inicio`,`duracion_minutos`,`url_flyer`,`es_publico`,`activo`,`id_cliente`,`confirmado_en`,`actualizado_en`,`cancelado_en`) VALUES
  (1,2,'ALQUILER_SALON','solicitudes_alquiler','Fiesta de 15 años - Luz',NULL,'Fiesta de quince años con servicio completo de catering, meseras y sonido profesional.','2026-03-22','16:00:00',360,NULL,0,1,2,'2026-02-22','2026-02-24',NULL),
  (2,4,'BANDA','solicitudes_fechas_bandas','Reite - Tributo a La Renga',NULL,'Show completo del tributo a La Renga. Viernes noche. Fecha propia confirmada.','2026-03-30','22:00:00',180,NULL,1,1,1,'2026-02-22','2026-02-24',NULL),
  (3,5,'BANDA','solicitudes_fechas_bandas','Las Mentas en Vivo',NULL,'Show abierto al público de la banda Las Mentas. Rock alternativo de buena calidad.','2026-04-10','20:00:00',150,NULL,1,1,5,'2026-02-22','2026-02-24',NULL),
  (4,8,'TALLER','solicitudes_talleres','Taller de Masaje Descontracturante',NULL,'Sesión grupal de masaje descontracturante. Técnicas relajantes y terapéuticas.','2026-03-08','10:00:00',90,NULL,1,1,2,'2026-02-22','2026-02-24',NULL);
/*!40000 ALTER TABLE `eventos_confirmados` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `eventos_lineup`
--

LOCK TABLES `eventos_lineup` WRITE;
/*!40000 ALTER TABLE `eventos_lineup` DISABLE KEYS */;
/*!40000 ALTER TABLE `eventos_lineup` ENABLE KEYS */;
UNLOCK TABLES;

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
