#!/usr/bin/env bash
set -euo pipefail

# scripts/export_db_to_migrations.sh
# Exporta el contenido ACTUAL de la base de datos a un archivo SQL dentro de
# database/migrations/ como un "data-only" dump (uso de REPLACE INTO).
# Objetivo: después de un `./scripts/reset.sh` (o `./scripts/up.sh --migrate`),
# aplicar este archivo devolverá las filas exportadas al estado actual.
#
# Nota importante:
# - El dump **usa REPLACE INTO** (no CREATE TABLE). Será idempotente para filas
#   con la misma PK (reemplaza/actualiza), pero no elimina filas que existían
#   previamente en el seed/base y ya no existen en la DB actual.
# - Revisa el SQL generado antes de commitearlo a `database/migrations/`.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
COMPOSE_FILE="$ROOT_DIR/docker/docker-compose.yml"

# Detectar comando compose (preferir plugin)
if docker compose version >/dev/null 2>&1; then
  COMPOSE_CMD="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE_CMD="docker-compose"
else
  echo "❌ ERROR: docker compose / docker-compose no disponible" >&2
  exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
  echo "❌ ERROR: no se encontró $ENV_FILE" >&2
  exit 1
fi

# Cargar .env
set -a
source "$ENV_FILE"
set +a

: "Verificar variables mínimas" || true
if [ -z "${MARIADB_DATABASE:-}" ] || [ -z "${MARIADB_ROOT_PASSWORD:-}" ]; then
  echo "❌ ERROR: MARIADB_DATABASE o MARIADB_ROOT_PASSWORD no están definidas en $ENV_FILE" >&2
  exit 1
fi

# Verificar que el servicio mariadb esté en ejecución
DB_SERVICE="mariadb"
DB_CONTAINER_ID=$($COMPOSE_CMD -f "$COMPOSE_FILE" ps -q "$DB_SERVICE" 2>/dev/null || true)
if [ -z "$DB_CONTAINER_ID" ]; then
  echo "❌ ERROR: el servicio '$DB_SERVICE' no parece estar corriendo. Levántalo primero (./scripts/up.sh)." >&2
  exit 1
fi

# Verificar mysqldump disponible dentro del contenedor
if ! $COMPOSE_CMD -f "$COMPOSE_FILE" exec -T "$DB_SERVICE" sh -lc "command -v mysqldump >/dev/null 2>&1"; then
  echo "❌ ERROR: 'mysqldump' no está disponible dentro del contenedor '$DB_SERVICE'." >&2
  exit 1
fi

# Preparar nombre de archivo y cabecera
TS=$(date +%Y%m%d%H%M%S)
OUT_DIR="$ROOT_DIR/database/migrations"
mkdir -p "$OUT_DIR"
OUT_FILE="$OUT_DIR/${TS}_export_data.sql"

cat > "$OUT_FILE" <<EOF
-- ------------------------------------------------------------------
-- AUTO-GENERATED by scripts/export_db_to_migrations.sh
-- Database: ${MARIADB_DATABASE}
-- Host: 		hostname: $(hostname)
-- Date (UTC): 	$(date -u +"%Y-%m-%dT%H:%M:%SZ")
-- NOTE: This is a data-only dump using REPLACE INTO (idempotent updates)
--       Review the file before committing it into source control.
-- ------------------------------------------------------------------
SET FOREIGN_KEY_CHECKS=0;
START TRANSACTION;
EOF

# Ejecutar mysqldump (solo data, REPLACE INTO, complete-insert para legibilidad)
echo "Exportando datos de '${MARIADB_DATABASE}' a: $OUT_FILE"
$COMPOSE_CMD -f "$COMPOSE_FILE" exec -T "$DB_SERVICE" sh -lc \
  "mysqldump -u root -p\"$MARIADB_ROOT_PASSWORD\" --skip-add-drop-table --no-create-info --complete-insert --replace \"$MARIADB_DATABASE\"" >> "$OUT_FILE"

cat >> "$OUT_FILE" <<EOF
COMMIT;
SET FOREIGN_KEY_CHECKS=1;
-- End of export
EOF

echo "✅ Export completado: $OUT_FILE"

echo "Sugerencia: revisa el archivo y móntalo en 'database/migrations/' (ya está allí). Luego puedes ejecutar: ./scripts/up.sh --migrate o ./scripts/reset.sh para aplicarlo."